### ISSUE TITLE
Looking for Maintainer

### ISSUE THREAD

**Issue by jfryman** [voxpupuli/puppet-selinux#106]
Hello everyone,

I am looking for a maintainer for this module. I'm burnt. Quite hard. It has been a very long and tough 36 months for me both personally and professionally.

To that end, I would like to hand this over to someone who would like to take ownership of it. 

For all of you who have used this module, thanks for your support and I hope you continue to find value from it. I hope to see some of you around.

❤️

@jfryman

**Comment by nbeernink** [comment]
Hi James, I feel bad reading this news. I wish you all the best in the future. Perhaps you can transfer this project to https://github.com/voxpupuli? It was started with this situation in mind.

**Comment by jfryman** [comment]
Thanks @nbeernink. I think that's what will ultimately end up happening. I'm having a similar discussion for the nginx module. https://github.com/jfryman/puppet-nginx/issues/844#issuecomment-237995519

It makes sense, and I'm glad such a project exists.

**Comment by nbeernink** [comment]
Yeah I noticed the comment a bit later when I checked the issue-trackers on your other repositories. Still, I would hate to see this specific module die an unmaintained death because we use it every 30 minutes. ;)

**Comment by TJM** [comment]
@jfryman -- If you can't find someone a little more qualified, we can maintain it (LarkIT), but we are already stretched pretty thin. :)

~tommy

**Comment by jfryman** [comment]
This module has been transferred to the Vokpuppuli  namespace. The team is working on uploading to the forge, and once that has been updated I'll deprecate my module on the forge with the `999.999.999` version and a link to the new group.

To the @voxpupuli/collaborators team: thanks for existing, and for offering to curate this module.

I'll close this issue out once the final push is done.

**Comment by bastelfreak** [comment]
Hi @jfryman, can you release the 999.999.999 in your namespace please? We published a version of the module into our namespace.

**Comment by vinzent** [comment]
Hi @jfryman, reminder: could you release the 999.999.999 in your namespace to forge?

**Comment by jfryman** [comment]
Absolutely! Sorry this slipped past the filter.

Version `999.999.999` has been pushed to the forge. https://forge.puppet.com/jfryman/selinux
