### ISSUE TITLE
selinux::module fails when module contains more than .te file

### ISSUE THREAD

**Issue by maage** [voxpupuli/puppet-selinux#118]
Selinux module can contain .te, .if adn .fc files. See https://github.com/TresysTechnology/refpolicy/tree/master/policy/modules/services
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: not dependant
- Ruby: not dependant
- Distribution: not dependant
- Module version: 0.4.1
### How to reproduce (e.g Puppet code you use)

Create selinux module with multiple file types and try to use selinux::module to manage it.
### What behaviour did you get

So far I have not been able to manage single selinux module. Somehow te file ends up being directory.
### What behaviour did you expect instead

I expect to get similar behaviour than spiette/selinux. See:
https://github.com/spiette/puppet-selinux/blob/master/manifests/module.pp

Put selinux module files into puppet module files/selinux and then enable module by:

```
  ::selinux::module { 'myselmodulename':
    ensure => 'present',
    source => "puppet:///modules/${module_name}/selinux",
  }
```

**Comment by maage** [comment]
I have branch with fixes:
https://github.com/cybercom-finland/puppet-selinux/tree/module-source-directory-118
But I would like to have #117 fixed before.

**Comment by maage** [comment]
Also it might be benefical to restore API from spiette module totally, but I'm not sure about what I've dropped.
https://github.com/spiette/puppet-selinux/blob/master/manifests/module.pp

**Comment by vinzent** [comment]
In my opinion the `selinux::module` param should not synchronize a directory.

@maage if this is important for you please provide proposals on the issue #178 within the next few days.
