### ISSUE TITLE
prefix causes repeated module reinstalls

### ISSUE THREAD

**Issue by benohara** [voxpupuli/puppet-selinux#129]
Looks like its been raised before, we we're seeing modules try to reinstall each run.

Only way I could fix it was by setting $prefix = ''

Out modules do not have names with 'local_' prefixing in the .te

Hows this meant to work?

**Comment by benohara** [comment]
Actually, looks to be the output of semodule -l on EL7 not including module version numbers anymore!

**Comment by frapex** [comment]
@benohara: Regarding module version numbers. As of RHEL 7.3, the cmd "semodule -l" no longer returns version information. See https://bugzilla.redhat.com/show_bug.cgi?id=1391886 and https://bugzilla.redhat.com/show_bug.cgi?id=1392573.

Workaround / solution:
```
Selinux::Module {
  syncversion => false,
}
```

**Comment by zrice57** [comment]
+1

**Comment by edestecd** [comment]
#142 7.3 also requires the file name to match the module name, so prefixing only the file does not work.

**Comment by vinzent** [comment]
default prefix is now empty, merged with https://github.com/voxpupuli/puppet-selinux/pull/140 .

**Comment by bastelfreak** [comment]
Hi @benohara, this should be fixed in the latest release. Please reopen if you still experience issues.
