### ISSUE TITLE
Module in the Puppet forge is not up to date

### ISSUE THREAD

**Issue by ryayon** [voxpupuli/puppet-selinux#135]
Hi,

  Although it is not a technical issue, I do not understand why the module in the forge is not updated regularly.
  We miss some fixes if we want to get this module through the forge.

Regards

PS: same concern with other voxpopuli modules

**Comment by alexjfisher** [comment]
@ryayon Are you looking at the old forge location https://forge.puppet.com/jfryman/selinux or under voxpupuli's namespace at https://forge.puppet.com/puppet/selinux ?

**Comment by ryayon** [comment]
The voxpopuli one: **Version 0.5.0 released Sep 8th 2016**.
(Which is more than 2 months old now)

**Comment by alexjfisher** [comment]
Fair enough.  Just needed to check that's what you meant.  We do get lots of people who are confused by the namespace migrations. eg https://github.com/voxpupuli/puppet-nodejs/issues/179

**Comment by ryayon** [comment]
I understand.
Maybe, the README of the old modules/repositories should show up with bold, red and font size 50 that voxpopuli is the new/current maintainer :-)

**Comment by ryayon** [comment]
I close this issue as puppet forge is almost up to date now.
Thanks
