### ISSUE TITLE
Can't specify to remove permissive domain

### ISSUE THREAD

**Issue by vinzent** [voxpupuli/puppet-selinux#165]
## Affected Puppet, Ruby, OS and module versions/distributions

- Module version: 0.7.1

## How to reproduce (e.g Puppet code you use)

The defined type `selinux::permissive` does not allow to specify ensure => 'absent'.

## What behaviour did you expect instead

It should remove the permissive type if possible or fail otherwise.

## Any additional information you'd like to impart

* Removing a module which provides a domain which is set to permissive with semanage fails.
* related to https://github.com/voxpupuli/puppet-selinux/issues/147

**Comment by oranenj** [comment]
I actually have some code for this, but I didn't yet create a pull request. it's a really trivial provider to implement.
