### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by vinzent** [voxpupuli/puppet-selinux#184]
Larger changes are ahead. The download counter of the predecessor jfryman/selinux shows 4,203,495 downloads.

To clearly indicate by version numbers that whe introduce breaking changes, the next release should be labeld as 1.0.0 and shall be the last Puppet 3 module. 

The 1.0.0 will then be branched to the puppet3 branch and only accept bugfixes and added deprecation messages. 

Version 2.0.0 will contain Puppet 4 data types, new types/providers and streamlined parameter names in defined types. Most of the changes are breaking changes.

I've added milestones. You can view issues and PR's by milestone tag now:

Planned:
https://github.com/voxpupuli/puppet-selinux/milestones/1.0.0
https://github.com/voxpupuli/puppet-selinux/milestones/2.0.0

Unplanned:
https://github.com/voxpupuli/puppet-selinux/milestones/1.x.y
https://github.com/voxpupuli/puppet-selinux/milestones/2.x.y

**Comment by dhollinger** [comment]
Is 1.0.0 going to have breaking changes over the last 0.8.0 release or is the major version bump to 1.0.0 just to make it easier to read?

**Comment by vinzent** [comment]
> Is 1.0.0 going to have breaking changes over the last 0.8.0 release or
> is the major version bump to 1.0.0 just to make it easier to read?
>
1.0.0 shall mark the interfaces as stable according SemVer. The 2.0.0
release shall indicate that breaking changes are included. versions <
1.0.0 can introduce breaking changes at any time according Semver.

**Comment by vinzent** [comment]
> Is 1.0.0 going to have breaking changes over the last 0.8.0 release or
> is the major version bump to 1.0.0 just to make it easier to read?
>
ah, forgot to answer the breaking changes question: no 1.0 will not
introduce breaking changes compared to whats now in master.

**Comment by dhollinger** [comment]
> ah, forgot to answer the breaking changes question: no 1.0 will not
introduce breaking changes compared to whats now in master.

No big deal, the first answer sufficed. I had forgotten that the transition from 0.x.x to 1.0.0 in SemVer signifies a Stable release. Too used to see many "stable" modules using 0.x.x as their version number.

**Comment by nibalizer** [comment]
lgtm

**Comment by vinzent** [comment]
I'm preparing the release.

**Comment by vinzent** [comment]
comment of @rnelson0:

> selinux - 0.8.0 - deprecates puppet 3 selinux - 1.0.0 - removes puppet 3
> 
> All puppet 4 changes go against master. Releases would cascade from 1.0.0
> 
> All puppet 3 changes go against puppet3. Releases cascade from 0.8.0 but never reach 1.0.0. Only > security issues and severe breakage should be backported.
> 
> We can still release 0.8.1, 0.9.0, 0.10.0 etc for puppet 3 users, but we can move forward with removing deprecated functionality in the 1.x branch.
> (source: https://gist.github.com/rnelson0/2b68dd18b344ec923133304632cf0fbc)

**Comment by vinzent** [comment]
@rnelson0 

> How do I know when to release 1.0.0?
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on > which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards 
> compatibility, you should probably already be 1.0.0.
(http://semver.org/ - FAQ)

so my real question is maybe: do we (at least try) to follow Semantic Versioning? 

If yes: we should release 1.x.y with puppet3 support. 

For me a analogous problem is rubocop: new MINOR version and checks are renamed, removed, added and then things break. so rubocop is < 1.0.0 and its considered unstable according SemVer. If they would have been on 1.0.0 already they would have needed to bump to 2.0.0 for such changes (if they would follow Semver, it's just an example).

and a few personal opinions:

* if I'm on 0.8.0 (the latest before 1.0.0) I would try to install 1.0.0 without expecting changes because I always link Puppet to SemVer.
* according SemVer < 1.0.0 always can include breaking changes so releases 0.9.0 or 0.10.0 do not indicate they don't include breaking changes. With the 1.0.0 I like to indicate that there will no more breaking changes.

**Comment by vinzent** [comment]
@bastelfreak comment on IRC:

> In my opinion we are a software vendor to our users, and its a really bad approach if we encourage 
> them to use outdated software. And we do this if we support puppet3

I'm myself in the position that I'm working on sites which still are on Puppet 3. As much as I wan't they we're already on puppet4 there are valid reasons (not puppet related) that they are not. 

In every larger enterprise you will find legacy systems beause they're just not (yet?) agile and devops style.

**Comment by vinzent** [comment]
> so my real question is maybe: do we (at least try) to follow Semantic Versioning?
> If yes: we should release 1.x.y with puppet3 support.

commenting myself: If we use Semantic Versioning this module would need to be on 1.0.0 already for a long time.

**Comment by vinzent** [comment]
@rnelson0  on IRC:
> vinzentm: but you said in 0.8.0 it will be the last verson supporting p3

yes it's true. I only saw the puppet/selinux counter of 4000 on forge. after the release I was on jfryman/selinux and saw the counter: 4,209,280. And we are the followup of this module.

this changes the situation for me.

**Comment by vinzent** [comment]
I've created a poll to see what voxpupuli likes to do:

* yes = try to use SemVer, release a 1.0.0 before introducing many
breaking changes as 2.0.0
* no = release a 0.9.0 and do all the breaking changes with 1.0.0

Poll: http://doodle.com/poll/uxc4g3uwzxn9hm52

**Comment by alexjfisher** [comment]
Either are acceptable to me.  Having a major version release (1.0.0) for the puppet 3 release would probably make any future puppet3 branch releases easier to version.  This may never happen though.

**Comment by alexjfisher** [comment]
and like both @rnelson0 and @roidelapluie have said via the mailing list, I also think both options are compatible with SemVer.

**Comment by vinzent** [comment]
so i'm stopping here. we do release 0.9.0 what was planned for 1.0.0 by me and 2.0.0 will get 1.0.0. From a user perspective I'll find it no good decision but as pointed out its not strictly not semver and time is better invested to enhance and fix instead of discussing.
