### ISSUE TITLE
Remove CentOS 5 support

### ISSUE THREAD

**Issue by vinzent** [voxpupuli/puppet-selinux#190]
just tried to run the acceptance test for centos5.

* selinux::module fails (could not find /usr/share/selinux/devel/Makefile)
* selinux::permissive fails (semanage permissive doesn't exist at all)

CentOS 5 will be out of support on 2015-03 so I don't think its worth to invest time.

my proposed solution is to just remove Centos 5 support from metadata.json.

**Comment by vinzent** [comment]
legacy fedora releases should be removed too (Fedora 19-23) from metadata.json

**Comment by juniorsysadmin** [comment]
Fedora versions strings probably shouldn't be in the metadata.json

**Comment by vinzent** [comment]
>Fedora versions strings probably shouldn't be in the metadata.json

Why? What are yor arguments to remove it?

We do run tests against specific versions of fedora not against unspecified ones. 
As a user i'd like to see specific distro versions. 

What would happen to rspec puppet facts/facterdb tests which reads metadata json distro and version?

**Comment by vinzent** [comment]
I think we should list what we are running beaker acceptance tests for.

**Comment by oranenj** [comment]
I think it makes sense to support at least:
- CentOS/RHEL 6 (latest minor release, and the others best-effort only) and 7.3, and additionally RHEL 7.2 (CentOS doesn't usually support point releases after the next one is released AFAIK, but RHEL does, and not everyone will have updated to 7.3)
- Fedora 24 and 25

**Comment by oranenj** [comment]
I'm not sure if there are boxes available for testing against RHEL, but CentOS probably is close enough.
