### ISSUE TITLE
Support for Amazon Linux 5, 6, and 2016

### ISSUE THREAD

**Issue by dmei4380** [voxpupuli/puppet-selinux#200]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.2
- Ruby: 2
- Distribution: Amazon Linux 2016.09
- Module version: 0.8.0

## How to reproduce (e.g Puppet code you use)
use amazon linux and try to do:
class { selinux:
  mode => 'enforcing',
  type => 'targeted',
}
## What are you seeing
error and stops puppet run
## What behaviour did you expect instead
enable selinux
## Output log
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Amazon- is not supported at /etc/puppetlabs/code/environments/development/modules/selinux/manifests/params.pp:50:15
## Any additional information you'd like to impart
Please try to enable support for 2016 amazon Linux. It should be the same as Amazon Linux version 4. Your compatibility also shows Amazon 4, 5, and 6 are compatible however the params file appears to error out unless the version is 4.

**Comment by vinzent** [comment]
Please provide an example howto enable selinux on amazon linux manually. 

See also PR #193

**Comment by alexjfisher** [comment]
After dropping support in this module for puppet 3, it was established that the amazon OS support didn't actually work with puppet 4 *and* the metadata.json entries for Amazon Linux were also nonsense.  As such, it was removed until we could find an Amazon Linux user who could help us reinstate it. @dmei4380 This could be you!  If you could provide a PR for one or more recent Amazon Linux releases **running puppet 4** we'd be very grateful.

**Comment by vinzent** [comment]
@dmei4380 please reopen if you can provide steps how SELinux can be enabled on AmazonLinux.
