### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by vinzent** [voxpupuli/puppet-selinux#207]
* read https://voxpupuli.org/docs/#releasing-a-new-version-of-a-module
* generate changelog: https://voxpupuli.org/blog/2017/01/13/github_changelog_generator-usage/
* generate puppet strings docs

**Comment by oranenj** [comment]
The release rake task has been run.

**Comment by oranenj** [comment]
Release is now visible in the forge, but hmm. How does the documentation work?

**Comment by oranenj** [comment]
Looks like the documentation is in place too.

**Comment by oranenj** [comment]
added label to ignore this in the changelog
