### ISSUE TITLE
Fix acceptance tests with docker

### ISSUE THREAD

**Issue by cdenneen** [voxpupuli/puppet-selinux#223]
Running the shipped `docker/centos-7.yml` doesn't work.

`beaker-pe` required in Gemfile (PE functionality broken out)
Otherwise the following error occurs

```
An error occurred while loading ./spec/acceptance/class_spec.rb.
Failure/Error: run_puppet_install_helper unless ENV['BEAKER_provision'] == 'no'
NoMethodError:
  undefined method `install_pe_on' for main:Object
```

Adding `beaker-pe` results in the following:

```
An error occurred in a `before(:suite)` hook.
Failure/Error: on host, puppet('module', 'install', 'puppetlabs-stdlib'), acceptable_exit_codes: [0, 1]
Beaker::Host::CommandFailure:
  Host 'centos-7-x64' exited with 127 running:
   puppet module install puppetlabs-stdlib
  Last 200 lines of output were:
  	bash: puppet: command not found
```

Adding the following ENV gets past the installer issue:

`PUPPET_INSTALL_TYPE="agent" PUPPET_INSTALL_VERSION="1.10.1"` but now yields the following:

```
An error occurred in a `before(:suite)` hook.
Failure/Error: on(host, 'sed -i "s/SELINUX=.*/SELINUX=permissive/" /etc/selinux/config')
Beaker::Host::CommandFailure:
  Host 'centos-7-x64' exited with 2 running:
   sed -i "s/SELINUX=.*/SELINUX=permissive/" /etc/selinux/config
  Last 200 lines of output were:
  	sed: can't read /etc/selinux/config: No such file or directory
```

Trying to get past these because on a beaker test that has include of selinux class I'm getting the following:

```
     Failure/Error: apply_manifest_on(host, pp, :environment => puppet_env, :catch_failures =>true)
     Beaker::Host::CommandFailure:
       Host 'el' exited with 6 running:
        puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.hRHGnw
       Last 10 lines of output were:
       	Notice: /Stage[last]/Selinux::Package/Package[selinux-policy-devel]: Dependency Service[ip6tables] has failures: true
       	Warning: /Stage[last]/Selinux::Package/Package[selinux-policy-devel]: Skipping because of failed dependencies
       	Notice: /Stage[last]/Selinux::Config/File[/usr/share/selinux]: Dependency Service[ip6tables] has failures: true
       	Notice: /Stage[last]/Selinux::Config/File_line[set-selinux-config-to-disabled]: Dependency Service[ip6tables] has failures: true
       	Notice: /Stage[last]/Selinux::Config/Exec[change-selinux-status-to-disabled]: Dependency Service[ip6tables] has failures: true
       	Warning: /Stage[last]/Selinux::Config/File[/usr/share/selinux]: Skipping because of failed dependencies
       	Warning: /Stage[last]/Selinux::Config/File_line[set-selinux-config-to-disabled]: Skipping because of failed dependencies
       	Warning: /Stage[last]/Selinux::Config/Exec[change-selinux-status-to-disabled]: Skipping because of failed dependencies
       	Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
       	Notice: Applied catalog in 187.79 seconds
```

So I'm not sure if `selinux` supports docker at all.

**Comment by vinzent** [comment]
hey @cdenneen , actually selinux won't work in a container. you'll need a full blown VM for this. This is the cause for the `PUPPET_INSTALL_TYPE="agent" PUPPET_INSTALL_VERSION="1.10.1"` variant failing. 

How did you start the first one? IMHO without PUPPET_INSTALL_TYPE=agent it might install foss/pe (which isn't what you want and anyway won't work with Puppet >= 4 ). https://github.com/puppetlabs/beaker-puppet_install_helper suggests to set PUPPET_INSTALL_TYPE (and PUPPET_INSTALL_VERSION) to get the expected behaviour.

**Comment by cdenneen** [comment]
@vinzent 
the first one was started without beaker-pe in gemfile.
the second one was with beaker-pe in Gemfile but without PUPPET_INSTALL_TYPE or PUPPET_INSTALL_VERSION (this seems to work sometimes on certain machines but in this case is necessary)
the third was with these done and complains about missing files from the selinux package (which would be installed via the module if missing)
If docker isn't supported (the centos7 container I would think is pretty close to full blown VM with init command) maybe this module should have a wrapper to send warning "Docker not supported" but exit 0? This would allow profiles and other things tested with docker to run through their acceptance tests using docker or not?

**Comment by vinzent** [comment]
@cdenneen Docker is not not supported, but docker does not support selinux.  ;-) Selinux is happening "inside" the kernel and is not a normal application.

> f docker isn't supported (the centos7 container I would think is 
> pretty close to full blown VM with init command) maybe this module 
> should have a wrapper to send warning "Docker not supported" but exit 0? 

all ~76 voxpupuli modules share these nodesets (source is here: https://github.com/voxpupuli/modulesync_config/tree/master/moduleroot/spec/acceptance/nodesets). The nodesets aren't  specific for puppet-selinux. 

Howto run the acceptance test is documented here: https://github.com/voxpupuli/puppet-selinux#development 

You might figure out some way to check if it is runing in docker and bail out with a nice message in `spec/spec_helper_acceptance.rb` - I'm happy to accept a patch.

**Comment by cdenneen** [comment]
@vinzent Yes I know they are used with modulesync. Probably should be excluded with sync.yaml... yeah adding to spec/spec_helper_acceptance.rb won't help when selinux is added to a profile, this would need to be at the puppet code level to send warning message and exit with 0 code. I'll see if I can come up with something.

**Comment by lmayorga1980** [comment]
I am facing a similar issue where I need a master/agent setup with `pe`. Can someone share the configurations?
