### ISSUE TITLE
Amazon Linux support

### ISSUE THREAD

**Issue by clinty** [voxpupuli/puppet-selinux#230]
Please add support for Amazon Linux.  It should be similar to RHEL5, with
`$sx_fs_mount = '/selinux'` and `$package_name = 'policycoreutils'`

Output of `facter os`:

```
{
  architecture => "x86_64",
  distro => {
    codename => "n/a",
    description => "Amazon Linux AMI release 2017.03",
    id => "AmazonAMI",
    release => {
      full => "2017.03",
      major => "2017",
      minor => "03"
    },
    specification => ":base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "Amazon",
  release => {
    full => "2017.03",
    major => "2017",
    minor => "03"
  },
  selinux => {
    config_mode => "enforcing",
    current_mode => "enforcing",
    enabled => true,
    enforced => true,
    policy_version => "30"
  }
}
```

**Comment by oranenj** [comment]
Is there a way to test on Amazon Linux? IIRC the lack of good means to run tests was the main reason we dropped support during the 1.0.0 refactoring.

**Comment by clinty** [comment]
I don't think I understand the question.  Are you asking for a way that doesn't require running an Amazon Linux instance on AWS?

**Comment by oranenj** [comment]
@clinty: yes. Beaker tests for other operating systems can be run locally using Virtualbox.

**Comment by clinty** [comment]
If someone made an unofficial virtualbox image, would that suffice?

**Comment by oranenj** [comment]
A vagrant box that beaker can use would be fine, I suppose. I would accept patches for Amazon Linux even if it weren't tested, but without a way to run acceptance tests, there's no way to guarantee things will not break between releases.

**Comment by clinty** [comment]
Pull request sent.  I'll pursue the testing angle.

**Comment by clinty** [comment]
Does https://hub.docker.com/_/amazonlinux/ help at all?

**Comment by oranenj** [comment]
@clinty: This issue was closed by the pull req merge. You should probably create another issue for the testing stuff.

Unfortunately, SELinux can't really be tested inside a container, so it'll have to be a virtual machine.

It does look like there's an amazon linux vagrant box: https://app.vagrantup.com/mvbcoding/boxes/awslinux/

That is something which might be useful.
