### ISSUE TITLE
Module does not work with Fedora 26

### ISSUE THREAD

**Issue by vinzent** [voxpupuli/puppet-selinux#234]
Fedora 26 comes with Python 3 by default. Puppet sets LANG=C when executing external scripts and Python then outputs some UTF-8 warning on STDERR. Puppet mixes STDOUT and STDERR to one,  the script wrongly parses the output and based on that runs wrong commands which in turn fail. 

See also #220

**Comment by vinzent** [comment]
re-ran the acceptance tests. seems the python3 LANG=C issue is no issue anymore. all tests were successfull.

**Comment by bastelfreak** [comment]
Should we add fedora26 now to our metadata.json? is /usr/bin/python python3?

**Comment by ekohl** [comment]
```
$ cat /etc/redhat-release && ls -l /usr/bin/python
Fedora release 26 (Twenty Six)
lrwxrwxrwx. 1 root root 7  2 nov 19:42 /usr/bin/python -> python2
```

**Comment by bastelfreak** [comment]
awwww :(

**Comment by vinzent** [comment]
why should we care what python is used as long as it works?

**Comment by bastelfreak** [comment]
I was just curious.

**Comment by ekohl** [comment]
@bastelfreak the consensus in the community is that switching /usr/bin/python to python3 is a bad idea and will likely not happen for a long time. Applications using python3 are using /usr/bin/python3 and Fedora packages will rewrite the shebang in the build step.

**Comment by vinzent** [comment]
@ekohl ahh nice to know!
