### ISSUE TITLE
Skip exec "change-selinux-status-to-disabled" when current mode is enforcing or permissive

### ISSUE THREAD

**Issue by bjvrielink** [voxpupuli/puppet-selinux#245]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.9.4
- Ruby: 2.1.9p490
- Distribution: RHEL 7
- Module version: 1.5.0

```
## How to reproduce (e.g Puppet code you use)
class {'::selinux':
  mode => 'disabled',
}
```
```
$ getenforce 
Enforcing
```

## What are you seeing
Each run, the exec 'change-selinux-status-to-disabled' runs.

## What behaviour did you expect instead
The exec 'change-selinux-status-to-disabled' should not run. This is because 'setenforce disabled' is not a correct usage of the setenforce command.
```
# setenforce disabled
usage:  setenforce [ Enforcing | Permissive | 1 | 0 ]
```

**Comment by bjvrielink** [comment]
See PR #246

**Comment by ekohl** [comment]
Fixed in https://github.com/voxpupuli/puppet-selinux/pull/246. Thanks!
