### ISSUE TITLE
Puppet errors on nodes with SELinux disabled

### ISSUE THREAD

**Issue by blackknight36** [voxpupuli/puppet-selinux#286]
After switching to this module in our puppet environment I noticed that catalog compilation will produce errors on nodes which have SELinux disabled.  For example, the following errors are shown on one of our nodes.

```
Error: /Stage[main]/Apache/Selinux::Boolean[httpd_anon_write]/Selboolean[httpd_anon_write]: Could not evaluate: Execution of '/usr/sbin/getsebool httpd_anon_write' returned 1: /usr/sbin/getsebool:  SELinux is disabled                                                                                                                   
Error: /Stage[main]/Apache/Selinux::Boolean[httpd_can_network_connect]/Selboolean[httpd_can_network_connect]: Could not evaluate: Execution of '/usr/sbin/getsebool httpd_can_network_connect' returned 1: /usr/sbin/getsebool:  SELinux is disabled                                                                                        
Error: /Stage[main]/Apache/Selinux::Boolean[httpd_can_network_connect_db]/Selboolean[httpd_can_network_connect_db]: Could not evaluate: Execution of '/usr/sbin/getsebool httpd_can_network_connect_db' returned 1: /usr/sbin/getsebool:  SELinux is disabled                                                                               
Error: /Stage[main]/Apache/Selinux::Boolean[httpd_can_network_relay]/Selboolean[httpd_can_network_relay]: Could not evaluate: Execution of '/usr/sbin/getsebool httpd_can_network_relay' returned 1: /usr/sbin/getsebool:  SELinux is disabled                                                                                              
Error: /Stage[main]/Apache/Selinux::Boolean[httpd_can_sendmail]/Selboolean[httpd_can_sendmail]: Could not evaluate: Execution of '/usr/sbin/getsebool httpd_can_sendmail' returned 1: /usr/sbin/getsebool:  SELinux is disabled                                                                                                             
Error: /Stage[main]/Apache/Selinux::Boolean[httpd_execmem]/Selboolean[httpd_execmem]: Could not evaluate: Execution of '/usr/sbin/getsebool httpd_execmem' returned 1: /usr/sbin/getsebool:  SELinux is disabled                                                                                                                            
Error: /Stage[main]/Apache/Selinux::Boolean[httpd_use_nfs]/Selboolean[httpd_use_nfs]: Could not evaluate: Execution of '/usr/sbin/getsebool httpd_use_nfs' returned 1: /usr/sbin/getsebool:  SELinux is disabled
```
I've fixed this in our apache module with a simple if $facts['selinux'] check but it would be nice if that was not necessary.

**Comment by ekohl** [comment]
I don't think simply looking at `$facts['selinux']` is sufficient. If `selinux` was enabled during the run, the fact will still be false. On the other hand, I don't know if you might actually need a reboot before you can use `selboolean`.

**Comment by blackknight36** [comment]
@ekohl You would need a reboot if SELInux was changed from disabled to enforcing or permissive mode.  The node would also require a file system relabel which would be done at boot time.  The selboolean command will also fail if SELinux is disabled.  For example:

```
[root@server1 ~]# setsebool httpd_anon_write 1
setsebool:  SELinux is disabled.
[root@server1 ~]# echo $?
1
```

$facts['selinux'] returns false when SELinux is disabled.  The boolean provider should use this data to avoid running commands that will not work in the first place.  Whether SELinux *should* be enabled is another matter and should be handled by the main selinux class.  I've done this in our own custom SELinux module and it works pretty well.

**Comment by ekohl** [comment]
Looking at config.pp it appears you're correct. Could you come up with a PR?

**Comment by blackknight36** [comment]
@ekohl I can but it shouldn't require much more than wrapping the selboolean resource in an if statement.  We did this in our own custom module using a custom fact as follows.

```
define selinux::boolean ($value, $persistent=false) {
    if $facts['selinux_simple'] == true {
        $bool_value = $value ? {
            [true, 1] => 'on',
            [false, 0] => 'off',
            'on' => 'on',
            'off' => 'off',
            default => 'on',
        }

        selboolean { $name:
            persistent => $persistent,
            value      => $bool_value,
        }
    }               
}
```

$selinux_simple is a custom fact which pretty much works the same as $selinux.

**Comment by blackknight36** [comment]
My question right now is should the module display a notification when SELinux is disabled or simply skip the resource and do nothing?  I'd like to avoid excessive noise in our puppet reports and a notification message would cause tagmail to send out an email every time the agent runs.

**Comment by ekohl** [comment]
I think skipping is ok. In case you're going from disabled to permissive then it'll be applied in the next run. The module allows setting the mode so the admin has sufficient to enforce the correct state.

It does look like this was moved to the os hash in facter 3. Maybe we should be using os.selinux.enabled and we can rely on that being a proper boolean type.

**Comment by blackknight36** [comment]
One issue with that is I still have Fedora 20 nodes in production which don't have an os.selinux fact defined.  OTHO $facts['selinux'] works everywhere.

Yes, I know F20 is old...

**Comment by ekohl** [comment]
Personally I'm fine with using the legacy facts, especially when the new facts don't really provide additional value. Can you verify it's a proper boolean (`facter --json selinux`)?

**Comment by blackknight36** [comment]
@ekohl 

Yes, the fact returns as a boolean.

```
[root@server1 ~]# facter --json selinux
{
  "selinux": false
}
```

I'll submit a PR to address this issue soon.

**Comment by blackknight36** [comment]
I also just noticed a similar issue with the selinux::fcontext type.

Jul 17 14:51:11 host.example.com puppet-agent[5589]: (/Stage[main]/Selinux/Anchor[selinux::end]) Dependency Selinux_fcontext[/srv/git(/.*)?_a] has failures: true
Jul 17 14:51:11 host.example.com puppet-agent[5589]: (/Stage[main]/Selinux/Anchor[selinux::end]) Skipping because of failed dependencies
Jul 17 14:51:11 host.example.com puppet-agent[5589]: Could not find a suitable provider for selinux_fcontext

**Comment by blackknight36** [comment]
I've tested these changes on my dev node, errors are no longer shown when puppet runs.
