### ISSUE TITLE
RHEL8

### ISSUE THREAD

**Issue by Ronaldschouw** [voxpupuli/puppet-selinux#293]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: ALL
- Ruby:
- Distribution: RHEL8
- Module version: ALL

## How to reproduce (e.g Puppet code you use)
RHEL8 operatingsystemmajrelease is not supported 
## Any additional information you'd like to impart
Please rewrite spec/classes/selinux_package_spec.rb and manifests/params.pp to support RHEL8

**Comment by ghoneycutt** [comment]
Hi @Ronaldschouw could you take a crack at a PR? The VP community is very likely to help you out with the code, though less likely to just add a new OS that they might not be using.

**Comment by ekohl** [comment]
It's not listed in metadata.json because I haven't personally tested this but I did merge 07f07480a6a8fe1327d030f76ff05fa9fbd855be which made it work for my colleague. In theory it's a matter of running the test suite and adding it to metadata.json.

**Comment by blackknight36** [comment]
I've opened #294 to address this.  I've been doing some testing with RHEL 8 nodes and haven't seen any other issues with the module itself.

**Comment by ekohl** [comment]
Resolved in https://github.com/voxpupuli/puppet-selinux/pull/294
