### ISSUE TITLE
Missing CentOS 8 support

### ISSUE THREAD

**Issue by jehane** [voxpupuli/puppet-selinux#301]
#77  Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5 
- Ruby:
- Distribution: CentOS 8
- Module version: latest

Is it possible to add CentOS 8 support ?

**Comment by oranenj** [comment]
The master branch of the module does work on CentOS 8, but it's "officially" not supported until there's some sort of testing for it.

**Comment by jsmelser** [comment]
I am really looking for this as well.. We are starting to get our Redhat 8 installs going and selinux is a big part of it.

**Comment by alexjfisher** [comment]
@oranenj Do you know of anything currently broken, or do we just need a release out that includes the fixes already made?

**Comment by oranenj** [comment]
@alexjfisher I already sent in a fix for the only brokenness I've encountered so far, but I don't have very many CentOS 8 hosts in use yet so there might be something hiding. I'm not against releasing anyway though; at least it'd make people more likely to test the module on CentOS 8

**Comment by jsmelser** [comment]
Once an initial push is done, I can open bugs as I see them as well.

**Comment by alexjfisher** [comment]
OK.  Looks like it's [completely broken](https://github.com/voxpupuli/puppet-selinux/issues/311) by the latest puppet agent release though?

**Comment by jsmelser** [comment]
I have 6.4.4, is it later than that as I can test with this version of it is.

**Comment by ekohl** [comment]
The current released version is compatible. If you find any bugs, then please open an issue.
