### ISSUE TITLE
Facter 4 compatibilty

### ISSUE THREAD

**Issue by ekohl** [voxpupuli/puppet-selinux#318]
Since Facter 4 was released, it appears the `selinux_python_command.rb` fact has started to fail when `rpm` is not present. This happens when running tests on a non-Red Hat OS where `rpm` is not present:

> Error while resolving custom fact fact='selinux_python_command', resolution='<anonymous>': Could not execute 'rpm -q python3-libsemanage'

It looks like `Facter::Core::Execution.execute` now raises an exception when the command fails where previously it didn't.

**Comment by ekohl** [comment]
Looks like this was also an issue in early Facter 2: https://tickets.puppetlabs.com/browse/FACT-409

**Comment by alexjfisher** [comment]
ping @IrimieBogdan

**Comment by blackknight36** [comment]
Are you certain that the confine statement is working?  Seems like the exec statement shouldn't be evaluated at all on non-RedHat nodes although you would also run into issues on a RedHat based OS where rpm is not available.

**Comment by ekohl** [comment]
Note that this is in CI, which is always a bit different. I suspect the RH facts are loaded on an Ubuntu machine. That might mess up things.

**Comment by IrimieBogdan** [comment]
@ekohl thanks for the info, in the next release of Facter 4 (probably tomorrow) this will be fixed. `Facter::Core::Execution.execute` will no longer throw exception and will log a message if it failed to execute command.

**Comment by ekohl** [comment]
Great to hear. I'll revert https://github.com/theforeman/puppet-pulpcore/commit/011f84bcaab7b07440a763f39ecdf643f70cda76 to verify it's been fixed.

**Comment by IrimieBogdan** [comment]
@ekohl We have identified the problem, when running Facter 4 in a gem context, the exit code should be 0, even if there were errors. There is an [experimental fix](https://github.com/puppetlabs/facter-ng/tree/experimental_exit), but it will not get in today's release. You can expect the fix to get in early next week.

**Comment by ekohl** [comment]
Thanks for the update! https://github.com/theforeman/puppet-pulpcore/pull/83 should test that branch.

**Comment by ekohl** [comment]
It looks like that passes, but still outputs the error. Now that makes me wonder: were custom facts always executed in CI?

**Comment by IrimieBogdan** [comment]
@ekohl a new release of Facter 4 is out https://rubygems.org/gems/facter/versions/4.0.13 Please give it a try.

**Comment by ekohl** [comment]
Closing due to the new facter version.
