### ISSUE TITLE
Manage setroubleshootd/sealert?

### ISSUE THREAD

**Issue by jcpunk** [voxpupuli/puppet-selinux#327]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6
- Ruby: 2
- Distribution: EL7
- Module version: 3.2.0

## Any additional information you'd like to impart

Could this module be extended to also manage setroubleshootd (sometimes packaged as sealert) as well?

**Comment by igalic** [comment]
if someone provided a patch with at least a basic design for this issue, it might be easier to decide if this belongs hereor into itsown module
