### ISSUE TITLE
missing semanage tools on el8

### ISSUE THREAD

**Issue by granquet** [voxpupuli/puppet-selinux#333]
The module installs ```python3-libsemanage``` but still needs ```policycoreutils-python-utils``` to function.

I'm getting errors when applying my recipe:
```
Could not find a suitable provider for selinux_fcontext
Could not find a suitable provider for selinux_port
```

the issue gets fixed as soon as I install ```policycoreutils-python-utils```.

**Comment by granquet** [comment]
this seems to be a working fix for me:
```
diff --git a/lib/facter/selinux_python_command.rb b/lib/facter/selinux_python_command.rb
index 9b28c5b..fdfef04 100644
--- a/lib/facter/selinux_python_command.rb
+++ b/lib/facter/selinux_python_command.rb
@@ -4,7 +4,7 @@ Facter.add(:selinux_python_command) do
     if File.exist? '/usr/libexec/platform-python'
       # RHEL 8 / CentOS 8
       '/usr/libexec/platform-python'
-    elsif Facter::Core::Execution.execute('rpm -q python3-libsemanage') !~ %r{not installed}
+    elsif Facter::Core::Execution.execute('rpm -q python3-libsemanage policycoreutils-python-utils') !~ %r{not installed}
       'python3'
     else
       # This might be python 2 or 3. Keeping it at 'python' matches the module
```

any opinions? shall I create a PR?

**Comment by kenyon** [comment]
@granquet are you setting `selinux::manage_package: false`? Otherwise, by default, `policycoreutils-python-utils` is installed by this module.

**Comment by granquet** [comment]
you are right, I should have looked a bit harder at the code in selinux_package_spec.rb

I'm actually using puppet-selinux through voxpupuli/puppet-squid ... which, after a quick glance, do not seem to do anything funky either (at least I'm sure no one is touching selinux:manage_package, not me, not voxpupuli/puppet-squid).

the good news is that I'm now unable to reproduce. not sure what went wrong in the first place. probably something on my setup.
I'll re-open if I see this issue coming back.
