### ISSUE TITLE
The semanage_ports.py script needs to pick the correct version of python on a system with multiple installed

### ISSUE THREAD

**Issue by trevor-vaughan** [voxpupuli/puppet-selinux#335]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Any
- Ruby: Any
- Distribution: EL8
- Module version: Any

## Information

On systems with multiple python interpreters installed, one needs to be explicitly chosen so that the correct libraries are used.

I'm not exactly sure what the correct method for doing this is but it may be better to detect the system python using Ruby and then generate the script on the fly with the correct interpreter in place.

**Comment by trevor-vaughan** [comment]
Relevant information https://developers.redhat.com/blog/2019/05/07/what-no-python-in-red-hat-enterprise-linux-8/

**Comment by ekohl** [comment]
I would expect it to use the system Python via our custom fact.
https://github.com/voxpupuli/puppet-selinux/blob/4633c26380b9cb8d5c816f78dce332c223b07c91/lib/facter/selinux_python_command.rb#L4-L6

Then rather than using the shebang, it should use the interpreter from the facts.

Is this an actual problem that you can reproduce?

**Comment by trevor-vaughan** [comment]
Relevant #330 => I am also trying to build an RPM for EL8 and this is causing issues.

Suggestion:
* Remove the `#!` completely since it is not required for the code
* Remove the `selinux_python_command` and internalize the lookup in the provider since the fact isn't actually required by anything else.

**Comment by ekohl** [comment]
That sounds good to me. I would consider removing the fact as a breaking change but can deal with that. So perhaps first a PR to remove the need for the fact (which would be an enhancement) and then one to remove the fact?

**Comment by trevor-vaughan** [comment]
Sure, that's easy enough. Can mark the fact as deprecated.

**Comment by ekohl** [comment]
Sounds good to me.

**Comment by trevor-vaughan** [comment]
@ekohl I think this is good to go, would you mind giving it another look when you have a chance?
