### ISSUE TITLE
Error finding provider when using selinux_port

### ISSUE THREAD

**Issue by jeannegreulich** [voxpupuli/puppet-selinux#337]
I would like to use aelinux_port and other types/and providers provided by this module but not use the whole module to control selinux.

This requires that the packages for selinux be installed.  This module already has the logic for that in selinux::packages and all the hiera data that is set up but I can't use it without the whole module because it it private.

I have a fix that makes the package module public so it can be included in other modules when the type or providers are used  but does not require them to include the whole module.  It also will not conflict with the module if they do choose to include the module to control selinux.

**Comment by kenyon** [comment]
Closing per https://github.com/voxpupuli/puppet-selinux/pull/338#issuecomment-788522608
