### ISSUE TITLE
Amazon Linux ( CentOS ) is not supported

### ISSUE THREAD

**Issue by boxrick** [voxpupuli/puppet-selinux#58]
Amazon Linux is not detected and unfortunately doesn't work by default. A bit of hacking around and it works fine. 

osfamily => Linux
operatingsystem => Amazon

Are the facts.

**Comment by jfryman** [comment]
Would you mind submitting a PR? Would love to have this in. Thanks!

**Comment by vinzent** [comment]
was added: https://github.com/voxpupuli/puppet-selinux/commit/7ce4a7d1172f6795829fad7c78ab6583f70d3ed6

**Comment by juniorsysadmin** [comment]
Fixed by #111
