### ISSUE TITLE
Problem with undef from left operand of 'in' at module.pp:38

### ISSUE THREAD

**Issue by salderma** [voxpupuli/puppet-selinux#61]
Hi, I am using your module from puppetforge to deploy a simple selinux policy.te file to many nodes like so:

```
  selinux::module { 'puppetlocal':
    ensure => present,
    source => 'puppet:///modules/site/selinux/puppetlocal.te',
  }
```

All agents where this is applied fail with:

```
'undef' from left of operand of 'in' expression is not a string at <modulepath>/selinux/manifests/module.pp:38
```

I am not using any references or resources from your module anywhere else for these nodes manifests.  I am not following why there needs to be a global param defined to set the selinux policy.  Shouldn't this be a module param? Can you provide any advice?

Thanks!

**Comment by salderma** [comment]
Also it seems some times my systems have this in their puppet reports, and selinux is completely disabled...
```
(/Stage[main]/Selinux::Config/File_line[set-selinux-config-to-disabled]/ensure) created
```
Which is a nasty side effect.

**Comment by mikalsande** [comment]
I am facing the same problem. This module configures to be disabled by default, setting SELINUX=disabled in /etc/selinux/config. Then after reboot SELinux will be disabled and puppet will fail with this error:

"Error: Could not retrieve catalog from remote server: Error 400 on SERVER: 'undef' from left operand of 'in' expression is not a string at /etc/puppet/modules/selinux/manifests/module.pp:38 on node"

**Comment by mikalsande** [comment]
@salderma This problem seemes to be fixed in the 0.2.6 release.

**Comment by salderma** [comment]
@mikalsande you are correct.  I guess I'm just going to break it down and hardcode the params.pp to enforcing like you suggested in another issue.

**Comment by mikalsande** [comment]
It seems there was a bug related to this https://github.com/jfryman/puppet-selinux/issues/64

**Comment by thrnio** [comment]
The problem here seems to be the use of `$::selinux_config_policy`, which doesn't exist. It's not clear to me what that code is supposed to do.

**Comment by vinzent** [comment]
this should be addressd in the current version.

if you still see this problem, please re-open the issue.
