### ISSUE TITLE
When using 'module' to install selinux-module the selinux-mode is set to disabled.

### ISSUE THREAD

**Issue by wouteroostervld** [voxpupuli/puppet-selinux#64]
When using 'module' to install selinux module mode is set to disabled. (Probably because ::selinux-class is implicitly loaded by type module.)

Expected was that just installing a module would leave the selinux-mode as-is.

See comment on: https://github.com/jfryman/puppet-selinux/commit/86e9599a7ac25a8f8bd0f8dc2d9665ef3b697bff

**Comment by wouteroostervld** [comment]
I will attempt to fix this problem later this week.

**Comment by thrnio** [comment]
:+1: this confused me greatly and is poor behavior IMO, not to mention undocumented.

**Comment by thrnio** [comment]
This should be changed now :)

**Comment by vinzent** [comment]
this should be fixed already. please re-open if you still see this problem
