### ISSUE TITLE
selinux_current_mode core fact no longer exists

### ISSUE THREAD

**Issue by midnightblackwolf** [voxpupuli/puppet-selinux#74]
In config.pp you are checking for the value of the fact selinux_current_mode to see if a 'notice' that a reboot is required to fully disable selinux is logged. As of facter 2.2, that core fact no longer exists.
We're running 2015.2 and the equivalent fact in facter 3.1 is os.selinux.current_mode.

**Comment by midnightblackwolf** [comment]
The only notice that we see is:
![selinux](https://cloud.githubusercontent.com/assets/1176921/11673014/291c11c8-9dca-11e5-9955-ea6f1fe40718.jpg)
which happens over and over, on every run.

**Comment by vinzent** [comment]
can't reproduce:

```
#> /opt/puppetlabs/bin/facter selinux_current_mode
enforcing
#> /opt/puppetlabs/bin/puppet --version
4.8.1
#> /opt/puppetlabs/bin/facter --version
3.5.0 (commit 872c5707799c1c30925b632f20eab763ec03b5a4)
```

as long as Puppet 3.8.7  is supported the old name should be used.

**Comment by alexjfisher** [comment]
I think the fact *does* exist, but is only when selinux is enabled.
In facter 2, the code is quite easy to read.  There is a [`confine :selinux => true`](https://github.com/puppetlabs/facter/blob/2dded53ea223fe15e9b18243e20bdb94c5ec88cd/lib/facter/selinux.rb#L127)
In facter 3, `selinux_current_mode` is also a legacy fact, so won't appear in the command line output when you just run `facter` by itself.

> This legacy fact is hidden by default in Facter’s command-line output.

But it definitely still [exists](https://github.com/puppetlabs/facter/blob/dd9950819a90821320a9182522188c6c3ce7b5f6/lib/src/facts/resolvers/operating_system_resolver.cc#L206).
Again, it is [only set if selinux is enabled](https://github.com/puppetlabs/facter/blob/dd9950819a90821320a9182522188c6c3ce7b5f6/lib/src/facts/linux/operating_system_resolver.cc#L77).

**Comment by alexjfisher** [comment]
This issue is also 12 months old, so I'm going to close.
@midnightblackwolf Please feel free to open a new issue or reopen this one if you're still having problems.
